rename and hardcoding vermagic

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,6 +4,12 @@
 KERNEL_VER=`uname -r |sed s'/-/\./g' |cut -f 1,2,3 -d"."`
 ARCH=`uname -m`
 if [[ $ARCH =~ arm* ]]; then ARCH=arm; fi
+
+#todo hardcoding
+VERMAGIC=3.12.6-SMP-mod_unload
+#VERMAGIC=3.10.20-al-2.5.3_sa-SMP-mod_unload-ARMv7-p2v8
+#VERMAGIC=3.19.8-SMP-mod_unload
+
 #LIB_MODULE is defined as module path
 #LIB_FIRMWARE
 LOG_FILE=/tmp/dvb.log
@@ -76,22 +82,33 @@ case "$1" in
     ;;
 
   install)
-    KVER2=`echo ${KERNEL_VER} |cut -f 1,2 -d"."`
+	#expect modules in /lib/modules.tgz of running instance
+	# after tar xf, the layout is
+	# /lib/modules/3.10.20/<arch>/<vermagic>/*.ko
+	#             /3.12.6/<arch>/<vermagic>/*.ko
+	#             /firmware
+	#             /install.sh (this file)
+	KVER2=`echo ${KERNEL_VER} |cut -f 1,2 -d"."`
     #copy fw
-    cp -a firmware/* ${LIB_FIRMWARE}
+	
+	test ! -f /lib/modules.tgz && echo "Missing modules" && exit 1
+	SRC_DIR=/lib/modules
+	cd /lib; tar xf modules.tgz
+	cp -a ${SRC_DIR}/firmware/* ${LIB_FIRMWARE}
 
     #pick module by ver/arch
-    test -d release/${KERNEL_VER} && rdir=release/${KERNEL_VER}
-    test -z "${rdir}" && test -d release/${KVER2} && rdir=release/${KVER2}
-    if [ -z "${rdir}" ]; then
-	echo "Fail to locate modules"
-	exit 1
-    elif [ ! -d ${rdir}/${ARCH} ]; then
-	echo "Architecture not supported"
-	exit 1
-    fi
-    cp ${rdir}/${ARCH}/*.ko ${LIB_MODULE}
-    ;;
+	test -d ${SRC_DIR}/${KERNEL_VER} && rdir=${SRC_DIR}/${KERNEL_VER}
+	test -z "${rdir}" && test -d ${SRC_DIR}/${KVER2} && rdir=${SRC_DIR}/${KVER2}
+	if [ -z "${rdir}" ]; then
+		echo "Fail to locate modules"
+		exit 1
+	elif [ ! -d ${rdir}/${ARCH}/${VERMAGIC} ];
+		echo "Architecture not supported"
+		exit 1
+	fi
+	cp ${rdir}/${ARCH}/${VERMAGIC}/*.ko ${LIB_MODULE}
+	cp ${SRC_DIR}/install ${LIB_MODULE}/rc
+	;;
   uninstall)
     ;;
   *)
